<html>
<head>
<META http-equiv="Content-Type" content="text/html; charset=UTF-8">
<LINK TITLE="Style" HREF="help.css" TYPE="text/css" REL="stylesheet">
<title>8.1.
                                </title>
</head>
<body>
<h1>8.1.
                                <code>Failed. Unexpected exit from test</code>
</h1>
                
<p>
<b>Answer:</b> The test has completed in an unexpected manner.
                This could be caused by some sort of fault (e.g. a segmentation fault)
                or because the harness has detected a call to <code>System.exit</code>
                from the test.</p>

                
<p>Tests are not allowed to call <code>System.exit</code> because the
                test must have the ability to run in the same JVM as the harness.
                Calling <code>System.exit</code> while the test is running in this
                manner whould cause the harness itself to exit!  Instead of calling
                <code>System.exit()</code>, throw an exception.</p>

                
<p>Be warned that the AWT event thread does not propagate exceptions,
                so if the test was exiting from the event thread, it is not sufficient
                to simply throw an exception.  The test must set some variable which
                can be used to throw an exception from one of the methods called by
                the harness. (i.e. <code>init()</code>, <code>start()</code>,
                <code>stop()</code>, or <code>destroy()</code>)</p>
            
</body>
</html>
